export default function Demo() {
  return (
    <section className="relative py-32 px-6">
      <div className="max-w-4xl mx-auto">
        {/* Section header */}
        <div className="text-center mb-12">
          <p className="text-sm font-medium text-indigo-400 tracking-wider uppercase mb-3">Preview</p>
          <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">
            See what you get.
          </h2>
          <p className="max-w-lg mx-auto text-zinc-400">
            Every day at 5pm, a video like this lands in your S3 bucket.
          </p>
        </div>

        {/* Video frame */}
        <div className="rounded-2xl border border-white/[0.06] bg-white/[0.02] p-1.5 shadow-2xl shadow-black/30">
          <div className="relative rounded-xl bg-gradient-to-br from-[#0d0d14] to-[#111118] aspect-video flex items-center justify-center overflow-hidden">
            {/* Decorative grid */}
            <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.015)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.015)_1px,transparent_1px)] bg-[size:32px_32px]" />

            {/* Center content */}
            <div className="relative text-center px-6">
              <div className="w-20 h-20 mx-auto mb-6 rounded-full bg-gradient-to-br from-indigo-500/20 to-violet-500/20 border border-indigo-500/20 flex items-center justify-center">
                <svg width="32" height="32" viewBox="0 0 24 24" fill="none" className="text-indigo-400 ml-1">
                  <path d="M5 3l14 9-14 9V3z" fill="currentColor"/>
                </svg>
              </div>
              <p className="text-white font-medium mb-2">Daily Standup Video</p>
              <p className="text-sm text-zinc-500">March 2, 2026 &middot; 4 tickets completed</p>
            </div>

            {/* Bottom info bar */}
            <div className="absolute bottom-0 left-0 right-0 px-5 py-4 bg-gradient-to-t from-black/60 to-transparent">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-full bg-gradient-to-br from-indigo-500 to-violet-600" />
                  <div>
                    <p className="text-xs text-zinc-300 font-medium">Generated by Slackatar</p>
                    <p className="text-xs text-zinc-500">FAL.ai &middot; 00:45</p>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
                  <span className="text-xs text-zinc-400">HD 1080p</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Tech stack pills */}
        <div className="flex flex-wrap justify-center gap-3 mt-10">
          {["FAL.ai", "Linear API", "DigitalOcean S3", "Node.js", "Cron"].map((tech) => (
            <span
              key={tech}
              className="px-4 py-1.5 text-xs font-medium text-zinc-500 rounded-full border border-white/[0.06] bg-white/[0.02]"
            >
              {tech}
            </span>
          ))}
        </div>
      </div>
    </section>
  )
}
